---
- stat: path=/var/lib/docker
  register: links
- debug: msg="link does not exists"
  when: links.stat.islnk is undefined or not links.stat.islnk
- name: Remove docker directory if it is not a symlink
  file:
    state: absent
    path: /var/lib/docker
  when: links.stat.islnk is undefined or not links.stat.islnk
- name: Create docker directory in /home/
  file:
    state: directory
    path: /home/docker
- name: Link
  file: path=/var/lib/docker
        src=/home/docker
        state=link 
        force=yes
