---
- lvol:
    vg: fedora
    lv: data
    size: +100%FREE
- filesystem:
    fstype: ext4
    dev: /dev/mapper/fedora-data
- name: Mount data volume
  mount:
    path: /var/lib/libvirt/images/
    src: /dev/mapper/fedora-data
    fstype: ext4
    state: present
- name: Mount data volume
  mount:
    path: /var/lib/libvirt/images/
    src: /dev/mapper/fedora-data
    fstype: ext4
    state: mounted
