---
- name: Install build dependencies
  dnf:
    name: '{{ item }}'
    state: latest
  with_items:
    - python-firewall
    - vagrant
    - vagrant-libvirt
    - git
    - mercurial
    - golang
    - rsync
    - libvirt-client
    - libvirt-devel
    - docker
- group:
    name: docker
    state: present
- name: Add jenkins user to libvirt and docker group
  user:
    name: jenkins
    groups: libvirt,docker
    append: yes
- name: Enable Libvirt and Docker
  systemd:
    name: '{{ item }}'
    enabled: yes
  with_items:
    - virtlogd
    - libvirtd
    - docker
- name: Start Libvirt and Docker
  systemd:
    name: '{{ item }}'
    state: restarted
    daemon_reload: yes
  with_items:
    - virtlogd
    - libvirtd
    - docker
- name: Disable selinux, to not block rsync via SSH in Jenkins
  selinux:
    policy: targeted
    state: permissive
