---
- name: Install build dependencies
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - python-firewall
    - git
    - make
    - rsync
    - docker
- name: Add docker group for the jenkins user
  group:
    name: docker
    state: present
- name: Add jenkins user to docker group
  user:
    name: jenkins
    groups: docker
    append: yes
- name: Enable Docker
  systemd:
    name: '{{ item }}'
    enabled: yes
  with_items:
    - docker
- name: Start Docker
  systemd:
    name: '{{ item }}'
    state: restarted
    daemon_reload: yes
  with_items:
    - docker
- name: Disable selinux, to not block rsync via SSH in Jenkins
  selinux:
    policy: targeted
    state: permissive
