---
- name: Install jenkins RPM repo
  get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
  retries: 5
  delay: 10
- name: Install jenkins GPG key
  rpm_key:
    state: present
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
- name: Install jenkins
  dnf:
    name: '{{ item }}'
    state: latest
  with_items:
    - java
    - jenkins  
    - firewalld  
- name: Enable Firewalld
  systemd:
    name: firewalld
    enabled: yes
- name: Enable Jenkins
  systemd:
    name: jenkins
    enabled: yes
- lineinfile:
    path: /etc/sysconfig/jenkins
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'    
- name: Ensures init.groovy.d directory exists
  file: 
    path: /var/lib/jenkins/init.groovy.d/ 
    state: directory    
- template:
    src: "{{ role_path }}/templates/01-plugins.groovy"
    dest: /var/lib/jenkins/init.groovy.d/01-plugins.groovy
- template:
    src: "{{ role_path }}/templates/02-security.groovy"
    dest: /var/lib/jenkins/init.groovy.d/02-security.groovy
- template:
    src: "{{ role_path }}/templates/03-seed.groovy"
    dest: /var/lib/jenkins/init.groovy.d/03-seed.groovy
- template:
    src: "{{ role_path }}/templates/04-jobs.groovy"
    dest: /var/lib/jenkins/init.groovy.d/jobs.groovy
- template:
    src: "{{ role_path }}/templates/05-github.groovy"
    dest: /var/lib/jenkins/init.groovy.d/05-github.groovy
- name: Make sure the Jenkins service is running
  systemd:
    state: restarted
    daemon_reload: yes
    name: jenkins
- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200    
- name: Delete startup scripts with sensible data after jenkins started
  file:
    state: absent
    path: "/var/lib/jenkins/init.groovy.d/"
- firewalld:
    zone: public
    port: 8080/tcp
    permanent: true
    state: enabled
- firewalld:
    zone: public
    service: http
    permanent: true
    state: enabled
