- name: Install the latest version of Java
  yum:
    name: java
    state: latest
- user:
    name: jenkins
    shell: /bin/bash
    createhome: yes
- name: Creates jenkins workdir
  file:
    path: "{{ swarmRootDir }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775
- name: Download swarm client
  get_url:
    url: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/3.9/swarm-client-3.9.jar
    dest: /opt/swarm-client.jar
- name: Ensures systemd directory exists
  file: 
    path: /etc/systemd/system/
    state: directory    
- copy: 
    content: "{{ jenkinsPass }}" 
    dest: /opt/.pwd 
- name: Copy systemd file    
  template:
    src: "{{ role_path }}/templates/swarm.service"
    dest: /etc/systemd/system/swarm.service
- name: Copy labels file
  template:
    src: "{{ role_path }}/templates/labels"
    dest: "{{ swarmRootDir }}/labels"
- name: Make sure that  the swarm agent is running
  systemd:
    state: restarted
    daemon_reload: yes
    name: swarm
- name: Make sure that the swarm agent is started on boot
  systemd:
    name: swarm
    enabled: yes
- name: Disable nested virtualization
  modprobe:
    name: "kvm_intel"
    state: absent
- name: Enable nested virtualization
  modprobe:
    name: "kvm_intel"
    state: present
    params: "nested=1"
