---
- name: Check if ssh key exists
  delegate_to: 127.0.0.1
  run_once: true
  become: false
  stat:
    path: id_rsa_jenkins_master
  register: stat_result
- name: generate private ssh key
  local_action: command ssh-keygen -b 2048 -t rsa -f id_rsa_jenkins_master -q -N ""
  run_once: true
  become: false
  when: stat_result.stat.exists == False           
- name: make sure the .ssh directory exists  
  file:
    path: /home/jenkins/.ssh/
    state: directory
    mode: 0700
    owner: jenkins
    group: jenkins
- name: "tell the host about the ssh host {{ storeSshUrl }}."
  become_user: jenkins
  known_hosts:
    name: "{{ storeSshUrl }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -4 ' + storeSshUrl) }}"
